name = "good-expectationss"
main = "worker.js"
compatibility_date = "2024-09-23"

[assets]
directory = "."
binding = "ASSETS"
exclude = ["worker.js", "wrangler.toml", "functions/**", "package.json", "README.md"]
